### ISSUE TITLE
AttributeError: 'SendToUnrealPreferences' object has no attribute 'multicast_ttl'

### ISSUE THREAD

**Issue by Waldehyd** [poly-hammer/BlenderTools#54] opened 2024-07-31 20:57 UTC
Addon:Send to Unreal
 I clicked Pipeline > Export > Send to Unreal

OS: Windows
Addon Version: Send to Unreal 2.4.5
Blender Version:.Blender 4.2
Unreal Version: Unreal 5.32

Error Log:
Python: Traceback (most recent call last):
  File "C:\Users\Waldo\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\utilities.py", line 799, in is_unreal_connected
    unreal.bootstrap_unreal_with_rpc_server()
  File "C:\Users\Waldo\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\dependencies\unreal.py", line 193, in bootstrap_unreal_with_rpc_server
    result = run_commands(
             ^^^^^^^^^^^^^
  File "C:\Users\Waldo\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\dependencies\unreal.py", line 160, in run_commands
    remote_exec = remote_execution.RemoteExecution()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Waldo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\send2ue\dependencies\remote_execution.py", line 60, in __init__
    def remote_nodes(self):
                     ^^^^^^^
  File "C:\Users\Waldo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\send2ue\dependencies\remote_execution.py", line 38, in __init__
    Configuration data for establishing a remote connection with a UE4 instance running Python.
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SendToUnrealPreferences' object has no attribute 'multicast_ttl'

**Comment by JoshQuake** [comment] 2024-08-01 00:37
Heyo just to confirm, is this Send2UE 2.4.5 or 2.4.6?

**Comment by Waldehyd** [comment] 2024-08-01 07:20
It's 2.4.5
The new 2.4.6 version didn't work for me with the "module not found" error mentioned in the other issue

**Comment by jack-yao91** [comment] 2024-08-01 12:35
This probably happened when uninstalling the installing the old version with the same blender runtime. Can you try uninstalling, shutdown blender, start blender, then install the 2.4.5 addon? Let us know if that works. We are fixing 2.4.6

**Comment by jack-yao91** [comment] 2024-08-08 12:40
Closing this out. Re-open if the issue is not resolved. Thanks

**Closed by jack-yao91** 2024-08-08 12:40 UTC
Labels: bug
