### ISSUE TITLE
send to unreal give me error ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by Genius-pig** [poly-hammer/BlenderTools#69] opened 2024-08-07 10:06 UTC
### In the description paste in and edit the following:
* **Addon:**  Send to Unreal
* **Steps to Reproduce the Problem:**  I clicked Pipeline > Export > Push assets
* **Error Log:** Paste the full error log
![image](https://github.com/user-attachments/assets/d221b084-43cf-4a29-8ced-c4649458ffbb)

![image](https://github.com/user-attachments/assets/7fbc4a92-e3c7-4ee1-b646-37237385b623)

* **OS:**  Windows
* **Addon Version:** Send to Unreal 2.4.8
* **Blender Version:** Blender 4.2
* **Unreal Version:** Unreal 5.4.3

**Comment by tcoursey** [comment] 2024-08-07 14:24
I experienced the EXACT same thing.  Everything above is exactly the same for me.  

Screen shots, versions, Steps to produce etc.

**Comment by plumpdolphin** [comment] 2024-08-07 15:17
I was able to replicate this issue by installing the plugin fresh, both from the 2.4.8 zip on the release page and current committed version. A co-worker of mine is experiencing the same issue. _If you already have a working plugin, reproduction requires existing plugin version to be completely uninstalled._

Additionally, running the `Pipeline > Utilities > Start RPC Servers` command also warranted the same error with the exact same stacktrace as `Pipeline > Export > Push assets` because it's failing while establishing the connection, before it ever has a chance to hit the `Push Asset`-specific logic

**I have found a way to "fix" this is:**

1. First, install the original Epic Games version of the Send2UE plugin.
2. Run the `Push Assets` command (it throws the global Regex error).
3. Disable the Epic Games version.
4. Install the Poly Hammer version (note the reduced number of reported policy violations).
5. Now running `Push Assets` is successful.

It seems to be something to do with the restructuring of how the package imports it's dependencies, but I'm not sure what the fix would be at this time.

Hope this helps!

**Closed** 2024-08-08 01:21 UTC
Labels: bug
